//  VELVET  ·  modules/settings/CreditsPane.qml
//  The credits: who this shell is for and what it stands on. Written in the
//  current look's own cards and type.
import qs.config
import qs.services
import qs.components
import QtQuick

Item {
    id: root

    focus: true

    // the people, in order of appearance
    readonly property var people: [
        { name: "SUG & SANE", tag: "SnS", number: "27", note: "" }
    ]

    readonly property var stack: [
        { k: "SHELL", v: "QUICKSHELL ON HYPRLAND · QT 6" },
        { k: "SOUND", v: "EVERY SOUND PACK IS SYNTHESISED HERE — ASSETS/MAKE-SFX-PACKS.PY" },
        { k: "FONTS", v: "THE PIXEL FACE IS GENERATED BY ASSETS/MAKE-FONT.PY" }
    ]

    Flickable {
        id: flick

        anchors.fill: parent
        anchors.rightMargin: 8
        contentWidth: width
        contentHeight: col.implicitHeight + 40
        clip: true
        boundsBehavior: Flickable.StopAtBounds

        Column {
            id: col

            width: flick.width
            spacing: 26
            topPadding: 8

            // ── the head
            Column {
                width: parent.width
                spacing: 4

                P5Text {
                    display: true
                    text: "CREDITS"
                    color: Colours.ink
                    font.pixelSize: Appearance.font.size.title
                }
                P5Text {
                    text: "THE PEOPLE BEHIND IT, AND WHAT IT STANDS ON"
                    color: Colours.inkDim
                    font.pixelSize: Appearance.font.size.small
                    tracking: 2
                }
            }

            // ── SnS
            Repeater {
                model: root.people

                Item {
                    id: card

                    required property var modelData

                    width: col.width
                    height: Math.max(300, tagBox.height + 60)

                    readonly property bool hot: cardHover.hovered

                    Slash {
                        anchors.fill: parent
                        shear: 0
                        color: Colours.alpha(Colours.surface, 0.9)
                        borderColor: card.hot ? Colours.accent : Colours.alpha(Colours.ink, 0.12)
                        borderWidth: card.hot ? 2 : 1
                    }
                    HoverHandler {
                        id: cardHover
                    }

                    // the signature, in the shell's own type
                    Item {
                        id: tagBox

                        x: 24
                        y: 24
                        width: Math.min(parent.width * 0.5, 620)
                        height: Math.min(260, width * 0.5)
                        clip: true

                        Plate {
                            anchors.fill: parent
                            radius: Appearance.r(14)
                            color: Colours.alpha(Colours.accent, 0.12)
                            border.width: 1
                            border.color: Colours.alpha(Colours.accent, 0.4)
                        }
                        P5Text {
                            anchors.centerIn: parent
                            anchors.verticalCenterOffset: -8
                            display: true
                            text: card.modelData.tag
                            color: Colours.accent
                            font.pixelSize: tagBox.height * 0.56
                            scale: card.hot ? 1.04 : 1

                            Behavior on scale {
                                NumberAnimation {
                                    duration: Appearance.anim.normal
                                    easing.type: Easing.OutBack
                                }
                            }
                        }
                        P5Text {
                            x: tagBox.width - implicitWidth - 18
                            y: tagBox.height - implicitHeight - 10
                            display: true
                            text: card.modelData.number
                            color: Colours.alpha(Colours.ink, 0.7)
                            font.pixelSize: 40
                        }
                    }

                    Column {
                        x: tagBox.x + tagBox.width + 36
                        y: 30
                        width: parent.width - x - 30
                        spacing: 8

                        P5Text {
                            text: "THANK YOU"
                            color: Colours.accent
                            font.pixelSize: Appearance.font.size.small
                            font.weight: Font.Bold
                            tracking: 4
                        }
                        P5Text {
                            display: true
                            width: parent.width
                            text: card.modelData.name
                            color: Colours.ink
                            font.pixelSize: Appearance.font.size.hero * 0.62
                            elide: Text.ElideRight
                        }
                        Row {
                            spacing: 10

                            Repeater {
                                model: [`(${card.modelData.tag})`, card.modelData.number]

                                Slash {
                                    required property string modelData

                                    width: chipT.implicitWidth + 28
                                    height: 36
                                    shear: 0
                                    color: Colours.alpha(Colours.accent, 0.16)
                                    borderColor: Colours.alpha(Colours.accent, 0.5)
                                    borderWidth: 1

                                    P5Text {
                                        id: chipT

                                        anchors.centerIn: parent
                                        text: modelData
                                        color: Colours.accentInk
                                        font.pixelSize: Appearance.font.size.large
                                        font.weight: Font.Bold
                                        tracking: 1
                                    }
                                }
                            }
                        }
                        P5Text {
                            visible: card.modelData.note !== ""
                            width: parent.width
                            text: card.modelData.note
                            color: Colours.inkDim
                            font.pixelSize: Appearance.font.size.normal
                            wrapMode: Text.WordWrap
                        }
                    }
                }
            }

            // ── what it stands on
            Column {
                width: parent.width
                spacing: 10

                P5Text {
                    text: "BUILT WITH"
                    color: Colours.accent
                    font.pixelSize: Appearance.font.size.small
                    font.weight: Font.Bold
                    tracking: 4
                }

                Repeater {
                    model: root.stack

                    Item {
                        id: line

                        required property var modelData

                        width: col.width
                        height: 46

                        readonly property bool hot: lineHover.hovered

                        Slash {
                            anchors.fill: parent
                            shear: 0
                            color: line.hot ? Colours.alpha(Colours.accent, 0.1) : Colours.alpha(Colours.surface, 0.6)
                            borderColor: Colours.alpha(Colours.ink, line.hot ? 0.22 : 0.08)
                            borderWidth: 1
                            flat: true

                            Behavior on color {
                                ColorAnimation {
                                    duration: Appearance.anim.fast
                                }
                            }
                        }
                        HoverHandler {
                            id: lineHover
                        }
                        P5Text {
                            x: 18
                            anchors.verticalCenter: parent.verticalCenter
                            width: 130
                            text: line.modelData.k
                            color: Colours.accent
                            font.pixelSize: Appearance.font.size.small
                            font.weight: Font.Bold
                            tracking: 3
                        }
                        P5Text {
                            x: 160
                            anchors.verticalCenter: parent.verticalCenter
                            width: parent.width - 180
                            text: line.modelData.v
                            color: Colours.ink
                            font.pixelSize: Appearance.font.size.normal
                            elide: Text.ElideRight
                        }
                    }
                }
            }

            P5Text {
                text: `VELVET ${Qt.application.version || ""}`.trim()
                color: Colours.alpha(Colours.inkDim, 0.7)
                font.pixelSize: Appearance.font.size.tiny
                tracking: 3
            }
        }

        SmoothScroll {
            view: flick
        }
    }
}
